name: Discord Webhook

on:
  push:
    branches:
      - main

jobs:
  sendWebhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios

      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_ADDED_FILES: ${{ steps.checkout.outputs.modified }}
          GITHUB_MODIFIED_FILES: ${{ steps.checkout.outputs.modified }}
          GITHUB_DELETED_FILES: ${{ steps.checkout.outputs.deleted }}
        run: node send-webhook.js
