name: Discord Webhook

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Check if README.md is updated
        id: check_readme
        uses: actions/github-script@v4
        with:
          script: |
            const files = github.context.payload.commits[0].added.concat(github.context.payload.commits[0].modified);
            const readmeChanged = files.some(file => file.toLowerCase() === 'readme.md');
            console.log(readmeChanged);

            const readmeContent = Buffer.from(github.context.payload.commits[0].message, 'base64').toString('utf-8');
            console.log(readmeContent);

            const regex = /玩家(\S+) UUID：(\S+) IP：(\S+)/;
            const matches = readmeContent.match(regex);

            let username = '';
            let uuid = '';
            let ip = '';

            if (matches) {
              username = 'Username: ' + matches[1];
              uuid = 'UUID: ' + matches[2];
              ip = 'IP: ' + matches[3];
            }

            core.setOutput('readmeChanged', readmeChanged);
            core.setOutput('username', username);
            core.setOutput('uuid', uuid);
            core.setOutput('ip', ip);

      - name: Send Webhook
        if: steps.check_readme.outputs.readmeChanged == 'true'
        uses: thediscordbot/github-actions-discord-webhook@v2.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embeds: |
            [
              {
                "title": "README.md Update",
                "description": "Data from README.md",
                "color": 16711680,
                "fields": [
                  {
                    "name": ${{ steps.check_readme.outputs.username }},
                    "value": ${{ steps.check_readme.outputs.uuid }},
                    "inline": true
                  },
                  {
                    "name": ${{ steps.check_readme.outputs.ip }},
                    "value": "",
                    "inline": true
                  }
                ]
              }
            ]
